### ISSUE TITLE
 internal, implementation, error 

### ISSUE THREAD

**Issue by daslicht** [BorisMoore/jsrender-node-starter#1]
Hi,
when I run this:

```
https://github.com/BorisMoore/jsrender-node-starter/blob/master/index-helloworld.js
```

returning a simple string works.

My Folder structure is : 

```
/templates/helloworld.html
index.js
```

I get:

```
Debug: internal, implementation, error 
    TypeError: compiled is not a function: compiled is not a function
    at Object.renderer (/Users/daslicht/DEV/node/hapi/hello-hapi/node_modules/vision/lib/manager.js:141:36)
    at internals.Manager._loadPartials.internals.Manager._loadHelpers.internals.Manager.render.internals.Manager._prepare.internals.Manager._prepareEngine.internals.Manager._prepareTemplates.callback._path.internals.Manager._path.internals.Manager._render.compiled.template [as _render] (/Users/daslicht/DEV/node/hapi/hello-hapi/node_modules/vision/lib/manager.js:468:14)
    at Object.internals.Manager._loadPartials.internals.Manager._loadHelpers.internals.Manager.render.internals.Manager._prepare.internals.Manager._prepareEngine.internals.Manager._prepareTemplates.callback._path.internals.Manager._path.internals.Manager._render.internals.Manager._compile.internals.marshal.callback [as marshal] (/Users/daslicht/DEV/node/hapi/hello-hapi/node_modules/vision/lib/manager.js:562:13)
    at internals.Response._prepare.internals.Response._processPrepare.internals.Response._marshal.next [as _marshal] (/Users/daslicht/DEV/node/hapi/hello-hapi/node_modules/hapi/lib/response.js:464:22)
    at /Users/daslicht/DEV/node/hapi/hello-hapi/node_modules/hapi/lib/transmit.js:124:18
    at /Users/daslicht/DEV/node/hapi/hello-hapi/node_modules/hapi/lib/transmit.js:499:20
    at Object.exports.parallel (/Users/daslicht/DEV/node/hapi/hello-hapi/node_modules/hapi/node_modules/items/lib/index.js:47:9)
    at Object.exports.send.internals.marshal.internals.fail.internals.transmit.internals.state.Items.parallel [as state] (/Users/daslicht/DEV/node/hapi/hello-hapi/node_modules/hapi/lib/transmit.js:492:11)
    at Object.exports.send.internals.marshal.internals.state [as marshal] (/Users/daslicht/DEV/node/hapi/hello-hapi/node_modules/hapi/lib/transmit.js:98:15)
    at Object.exports.send.callback [as send] (/Users/daslicht/DEV/node/hapi/hello-hapi/node_modules/hapi/lib/transmit.js:30:15)


```

Using Node 4.2.2 and the following dependencies:

```
    "hapi": "^11.1.1",
    "inert": "^3.2.0",
    "jsrender": "0.0.3",
    "path": "^0.12.7",
    "vision": "^4.0.1"
```

**Comment by daslicht** [comment]
Looks like the version on npm is outdated ?

With:
```
"jsrender": "^1.0.0-rc.70",
```
It is working !

**Comment by BorisMoore** [comment]
Correct - that was the issue, but I don't understand what made you get that version - 0.0.3. On NPM I have https://www.npmjs.com/package/jsrender : borismoore borismoore published 2 months ago
1.0.0-rc.70 is the latest of 7 releases

Did you install into an empty folder with no package.json, and no previous installs of jsrender?

This is important. When I do a fresh install I get the latest version, so I am concerned that others also get the latest. See also this https://github.com/BorisMoore/jsrender/issues/278 where someone reported a similar problem.

**Comment by daslicht** [comment]
you are correct, thats really strange. 
As far as I remember I just did a 
npm init
npm install jsrender --save

**Comment by BorisMoore** [comment]
That's weird. And you had never previously installed jsrender of any flavor, from npm?

**Comment by daslicht** [comment]
Nope :) I just give it a try today.

**Comment by BorisMoore** [comment]
Good. Can you retry the install - to see if I can figure out repro for this 0.0.3 scenario?

Copying also this from:

That is strange. It looks like you are getting this https://github.com/defunctzombie/node-jsrender/blob/master/package.json - rather than this: https://github.com/BorisMoore/jsrender/releases

Here is more context, copied from https://github.com/BorisMoore/jsrender/issues/278:

The jsrender name was originally associated with the https://github.com/defunctzombie/node-jsrender repo, and was subsequently moved to https://github.com/BorisMoore/jsrender.

Also adding @defunctzombie. Roman, do you have any ideas as to how people could be getting your 0.0.3 when they do a fresh install of jsrender?

**Comment by daslicht** [comment]
anything fine now, when I install it now I get the correct version:
```
"jsrender": "^1.0.0-rc.70"
```
I still dont know how I got the other version :/

**Comment by BorisMoore** [comment]
OK - thank you very much for testing that. Appreciated. If you get any ideas about how it happened, let me know - I am concerned about this issue.

Maybe Roman Shtylman (@defunctzombie) might have some clues. I hope I can get to figure this out!

**Comment by daslicht** [comment]
I will ! Thank you !

**Comment by defunctzombie** [comment]
Only thing that comes to mind is if you had specifically had a previous version in your package.json file

**Comment by BorisMoore** [comment]
I did finally get information from the npm support team - and the  explanation is apparently as follows:

> Current npm versions will, if you say "npm install jsrender" use the value of the latest tag and install v1.0.0-rc.70. By current versions, I mean npm@3.4.1 or later.

> https://github.com/npm/npm/blob/master/CHANGELOG.md#v341-2015-11-12
> Earlier npm versions would look for the first version that matched *, which is 0.0.3, due to prereleases not matching ranges.

So the fix will be to use version numbers like 0.9.71 rather than 1.0.0-rc.71.

I will switch to the 0.9.71 style from the next update onwards.

**Comment by daslicht** [comment]
aha ! thats it, I played around with different versions of node and npm sicne things do not worked properly with node 4.

**Comment by daslicht** [comment]
something else, who is using js views / render in production ?

**Comment by BorisMoore** [comment]
Well it is not easy to know that. For example in GitHub there are about 11,000 instances of code referencing jsrender, and close to 4000 referencing jsviews. How many of them are used in production. Difficult to say. How many outside GitHub - also difficult. 

But a couple of examples of major production sites that I do know about:

www.outlook.com uses JsViews very intensively  as in: `<script id="inboxPageTemplate" type="text/x-jsrender">
    {^{inboxControl inbox=#data ~layout=Layout ~categoryList=CategoryList ~folderList=FolderList ~search=Search ~readMessage=ReadMessage ~rightRail=RightRail ~messageList=MessageList/}}
</script>

The Microsoft Azure management portal (https://portal.azure.com) has used JsViews very extensively.

www.workspace.com uses JsViews very extensively too.

But mostly people don't contact me to let me know about their JsViews or JsRender sites. Just as was the case with jQuery Templates. I by accident looked at the source code of www.pandora.com pages, for example, and discovered they are using jQuery Templates throughout their UI.

**Comment by daslicht** [comment]
Sounds great , so there is no argument against using JsViews regarding user base and future.
You know, that's one of the first things clients or colleges ask you.

**Comment by BorisMoore** [comment]
No, of course, not at all...
